// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_integrations

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createIntegrationStmt, err = db.PrepareContext(ctx, createIntegration); err != nil {
		return nil, fmt.Errorf("error preparing query CreateIntegration: %w", err)
	}
	if q.getIntegrationStmt, err = db.PrepareContext(ctx, getIntegration); err != nil {
		return nil, fmt.Errorf("error preparing query GetIntegration: %w", err)
	}
	if q.listIntegrationsByOrgStmt, err = db.PrepareContext(ctx, listIntegrationsByOrg); err != nil {
		return nil, fmt.Errorf("error preparing query ListIntegrationsByOrg: %w", err)
	}
	if q.updateIntegrationStmt, err = db.PrepareContext(ctx, updateIntegration); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateIntegration: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createIntegrationStmt != nil {
		if cerr := q.createIntegrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createIntegrationStmt: %w", cerr)
		}
	}
	if q.getIntegrationStmt != nil {
		if cerr := q.getIntegrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIntegrationStmt: %w", cerr)
		}
	}
	if q.listIntegrationsByOrgStmt != nil {
		if cerr := q.listIntegrationsByOrgStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listIntegrationsByOrgStmt: %w", cerr)
		}
	}
	if q.updateIntegrationStmt != nil {
		if cerr := q.updateIntegrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateIntegrationStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	createIntegrationStmt     *sql.Stmt
	getIntegrationStmt        *sql.Stmt
	listIntegrationsByOrgStmt *sql.Stmt
	updateIntegrationStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		createIntegrationStmt:     q.createIntegrationStmt,
		getIntegrationStmt:        q.getIntegrationStmt,
		listIntegrationsByOrgStmt: q.listIntegrationsByOrgStmt,
		updateIntegrationStmt:     q.updateIntegrationStmt,
	}
}
