// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integrations.sql

package db_integrations

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (org_id, type, credentials)
VALUES ($1, $2, $3)
RETURNING id, org_id, type, credentials, created_at, updated_at
`

type CreateIntegrationParams struct {
	OrgID       uuid.NullUUID   `json:"org_id"`
	Type        string          `json:"type"`
	Credentials json.RawMessage `json:"credentials"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.queryRow(ctx, q.createIntegrationStmt, createIntegration, arg.OrgID, arg.Type, arg.Credentials)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, org_id, type, credentials, created_at, updated_at FROM integrations WHERE id=$1
`

func (q *Queries) GetIntegration(ctx context.Context, id uuid.UUID) (Integration, error) {
	row := q.queryRow(ctx, q.getIntegrationStmt, getIntegration, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationsByOrg = `-- name: ListIntegrationsByOrg :many
SELECT id, org_id, type, credentials, created_at, updated_at FROM integrations WHERE org_id=$1
`

func (q *Queries) ListIntegrationsByOrg(ctx context.Context, orgID uuid.NullUUID) ([]Integration, error) {
	rows, err := q.query(ctx, q.listIntegrationsByOrgStmt, listIntegrationsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.Credentials,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegration = `-- name: UpdateIntegration :one
UPDATE integrations SET type=$2, credentials=$3, updated_at=now()
WHERE id=$1 RETURNING id, org_id, type, credentials, created_at, updated_at
`

type UpdateIntegrationParams struct {
	ID          uuid.UUID       `json:"id"`
	Type        string          `json:"type"`
	Credentials json.RawMessage `json:"credentials"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (Integration, error) {
	row := q.queryRow(ctx, q.updateIntegrationStmt, updateIntegration, arg.ID, arg.Type, arg.Credentials)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.Credentials,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
