// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_integrations

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Integration struct {
	ID          uuid.UUID       `json:"id"`
	OrgID       uuid.NullUUID   `json:"org_id"`
	Type        string          `json:"type"`
	Credentials json.RawMessage `json:"credentials"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}
