// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_integrations

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error)
	GetIntegration(ctx context.Context, id uuid.UUID) (Integration, error)
	ListIntegrationsByOrg(ctx context.Context, orgID uuid.NullUUID) ([]Integration, error)
	UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (Integration, error)
}

var _ Querier = (*Queries)(nil)
