// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_executions

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createExecutionStmt, err = db.PrepareContext(ctx, createExecution); err != nil {
		return nil, fmt.Errorf("error preparing query CreateExecution: %w", err)
	}
	if q.createNodeLogStmt, err = db.PrepareContext(ctx, createNodeLog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateNodeLog: %w", err)
	}
	if q.getExecutionStmt, err = db.PrepareContext(ctx, getExecution); err != nil {
		return nil, fmt.Errorf("error preparing query GetExecution: %w", err)
	}
	if q.listExecutionsByWorkflowStmt, err = db.PrepareContext(ctx, listExecutionsByWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query ListExecutionsByWorkflow: %w", err)
	}
	if q.listNodeLogsByExecutionStmt, err = db.PrepareContext(ctx, listNodeLogsByExecution); err != nil {
		return nil, fmt.Errorf("error preparing query ListNodeLogsByExecution: %w", err)
	}
	if q.updateExecutionStatusStmt, err = db.PrepareContext(ctx, updateExecutionStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateExecutionStatus: %w", err)
	}
	if q.updateNodeLogStmt, err = db.PrepareContext(ctx, updateNodeLog); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateNodeLog: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createExecutionStmt != nil {
		if cerr := q.createExecutionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createExecutionStmt: %w", cerr)
		}
	}
	if q.createNodeLogStmt != nil {
		if cerr := q.createNodeLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createNodeLogStmt: %w", cerr)
		}
	}
	if q.getExecutionStmt != nil {
		if cerr := q.getExecutionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getExecutionStmt: %w", cerr)
		}
	}
	if q.listExecutionsByWorkflowStmt != nil {
		if cerr := q.listExecutionsByWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listExecutionsByWorkflowStmt: %w", cerr)
		}
	}
	if q.listNodeLogsByExecutionStmt != nil {
		if cerr := q.listNodeLogsByExecutionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listNodeLogsByExecutionStmt: %w", cerr)
		}
	}
	if q.updateExecutionStatusStmt != nil {
		if cerr := q.updateExecutionStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateExecutionStatusStmt: %w", cerr)
		}
	}
	if q.updateNodeLogStmt != nil {
		if cerr := q.updateNodeLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateNodeLogStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	createExecutionStmt          *sql.Stmt
	createNodeLogStmt            *sql.Stmt
	getExecutionStmt             *sql.Stmt
	listExecutionsByWorkflowStmt *sql.Stmt
	listNodeLogsByExecutionStmt  *sql.Stmt
	updateExecutionStatusStmt    *sql.Stmt
	updateNodeLogStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		createExecutionStmt:          q.createExecutionStmt,
		createNodeLogStmt:            q.createNodeLogStmt,
		getExecutionStmt:             q.getExecutionStmt,
		listExecutionsByWorkflowStmt: q.listExecutionsByWorkflowStmt,
		listNodeLogsByExecutionStmt:  q.listNodeLogsByExecutionStmt,
		updateExecutionStatusStmt:    q.updateExecutionStatusStmt,
		updateNodeLogStmt:            q.updateNodeLogStmt,
	}
}
