// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package db_executions

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (workflow_id, org_id, input, status)
VALUES ($1, $2, $3, 'queued')
RETURNING id, workflow_id, org_id, status, input, output, created_at, updated_at
`

type CreateExecutionParams struct {
	WorkflowID uuid.NullUUID         `json:"workflow_id"`
	OrgID      uuid.NullUUID         `json:"org_id"`
	Input      pqtype.NullRawMessage `json:"input"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.queryRow(ctx, q.createExecutionStmt, createExecution, arg.WorkflowID, arg.OrgID, arg.Input)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNodeLog = `-- name: CreateNodeLog :one
INSERT INTO nodes_logs (execution_id, node_id, status, input)
VALUES ($1, $2, $3, $4)
RETURNING id, execution_id, node_id, status, input, output, error, created_at, updated_at
`

type CreateNodeLogParams struct {
	ExecutionID uuid.NullUUID         `json:"execution_id"`
	NodeID      string                `json:"node_id"`
	Status      sql.NullString        `json:"status"`
	Input       pqtype.NullRawMessage `json:"input"`
}

func (q *Queries) CreateNodeLog(ctx context.Context, arg CreateNodeLogParams) (NodesLog, error) {
	row := q.queryRow(ctx, q.createNodeLogStmt, createNodeLog,
		arg.ExecutionID,
		arg.NodeID,
		arg.Status,
		arg.Input,
	)
	var i NodesLog
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.NodeID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT id, workflow_id, org_id, status, input, output, created_at, updated_at FROM executions WHERE id = $1
`

func (q *Queries) GetExecution(ctx context.Context, id uuid.UUID) (Execution, error) {
	row := q.queryRow(ctx, q.getExecutionStmt, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExecutionsByWorkflow = `-- name: ListExecutionsByWorkflow :many
SELECT id, workflow_id, org_id, status, input, output, created_at, updated_at FROM executions WHERE workflow_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListExecutionsByWorkflow(ctx context.Context, workflowID uuid.NullUUID) ([]Execution, error) {
	rows, err := q.query(ctx, q.listExecutionsByWorkflowStmt, listExecutionsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.OrgID,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeLogsByExecution = `-- name: ListNodeLogsByExecution :many
SELECT id, execution_id, node_id, status, input, output, error, created_at, updated_at FROM nodes_logs WHERE execution_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListNodeLogsByExecution(ctx context.Context, executionID uuid.NullUUID) ([]NodesLog, error) {
	rows, err := q.query(ctx, q.listNodeLogsByExecutionStmt, listNodeLogsByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodesLog
	for rows.Next() {
		var i NodesLog
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.NodeID,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE executions
SET status=$2, output=$3, updated_at=now()
WHERE id=$1
RETURNING id, workflow_id, org_id, status, input, output, created_at, updated_at
`

type UpdateExecutionStatusParams struct {
	ID     uuid.UUID             `json:"id"`
	Status sql.NullString        `json:"status"`
	Output pqtype.NullRawMessage `json:"output"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error) {
	row := q.queryRow(ctx, q.updateExecutionStatusStmt, updateExecutionStatus, arg.ID, arg.Status, arg.Output)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.OrgID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNodeLog = `-- name: UpdateNodeLog :one
UPDATE nodes_logs
SET status=$2, output=$3, error=$4, updated_at=now()
WHERE id=$1
RETURNING id, execution_id, node_id, status, input, output, error, created_at, updated_at
`

type UpdateNodeLogParams struct {
	ID     uuid.UUID             `json:"id"`
	Status sql.NullString        `json:"status"`
	Output pqtype.NullRawMessage `json:"output"`
	Error  sql.NullString        `json:"error"`
}

func (q *Queries) UpdateNodeLog(ctx context.Context, arg UpdateNodeLogParams) (NodesLog, error) {
	row := q.queryRow(ctx, q.updateNodeLogStmt, updateNodeLog,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.Error,
	)
	var i NodesLog
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.NodeID,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
