// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_executions

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Execution struct {
	ID         uuid.UUID             `json:"id"`
	WorkflowID uuid.NullUUID         `json:"workflow_id"`
	OrgID      uuid.NullUUID         `json:"org_id"`
	Status     sql.NullString        `json:"status"`
	Input      pqtype.NullRawMessage `json:"input"`
	Output     pqtype.NullRawMessage `json:"output"`
	CreatedAt  sql.NullTime          `json:"created_at"`
	UpdatedAt  sql.NullTime          `json:"updated_at"`
}

type NodesLog struct {
	ID          uuid.UUID             `json:"id"`
	ExecutionID uuid.NullUUID         `json:"execution_id"`
	NodeID      string                `json:"node_id"`
	Status      sql.NullString        `json:"status"`
	Input       pqtype.NullRawMessage `json:"input"`
	Output      pqtype.NullRawMessage `json:"output"`
	Error       sql.NullString        `json:"error"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}
