// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_executions

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error)
	CreateNodeLog(ctx context.Context, arg CreateNodeLogParams) (NodesLog, error)
	GetExecution(ctx context.Context, id uuid.UUID) (Execution, error)
	ListExecutionsByWorkflow(ctx context.Context, workflowID uuid.NullUUID) ([]Execution, error)
	ListNodeLogsByExecution(ctx context.Context, executionID uuid.NullUUID) ([]NodesLog, error)
	UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error)
	UpdateNodeLog(ctx context.Context, arg UpdateNodeLogParams) (NodesLog, error)
}

var _ Querier = (*Queries)(nil)
