// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_users

import (
	"database/sql"

	"github.com/google/uuid"
)

type Org struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Plan      sql.NullString `json:"plan"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	OrgID        uuid.NullUUID  `json:"org_id"`
	Email        string         `json:"email"`
	Name         sql.NullString `json:"name"`
	PasswordHash string         `json:"password_hash"`
	Role         sql.NullString `json:"role"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}
