// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credits.sql

package db_credits

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addCreditEntry = `-- name: AddCreditEntry :one
INSERT INTO credits_ledger (org_id, execution_id, amount, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, execution_id, amount, reason, created_at
`

type AddCreditEntryParams struct {
	OrgID       uuid.NullUUID  `json:"org_id"`
	ExecutionID uuid.NullUUID  `json:"execution_id"`
	Amount      string         `json:"amount"`
	Reason      sql.NullString `json:"reason"`
}

func (q *Queries) AddCreditEntry(ctx context.Context, arg AddCreditEntryParams) (CreditsLedger, error) {
	row := q.queryRow(ctx, q.addCreditEntryStmt, addCreditEntry,
		arg.OrgID,
		arg.ExecutionID,
		arg.Amount,
		arg.Reason,
	)
	var i CreditsLedger
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ExecutionID,
		&i.Amount,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgCredits = `-- name: GetOrgCredits :one
SELECT SUM(amount) as total_credits FROM credits_ledger WHERE org_id=$1
`

func (q *Queries) GetOrgCredits(ctx context.Context, orgID uuid.NullUUID) (int64, error) {
	row := q.queryRow(ctx, q.getOrgCreditsStmt, getOrgCredits, orgID)
	var total_credits int64
	err := row.Scan(&total_credits)
	return total_credits, err
}
