// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_credits

import (
	"database/sql"

	"github.com/google/uuid"
)

type CreditsLedger struct {
	ID          uuid.UUID      `json:"id"`
	OrgID       uuid.NullUUID  `json:"org_id"`
	ExecutionID uuid.NullUUID  `json:"execution_id"`
	Amount      string         `json:"amount"`
	Reason      sql.NullString `json:"reason"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type OrgsCredit struct {
	OrgID        uuid.UUID      `json:"org_id"`
	TotalCredits sql.NullString `json:"total_credits"`
	UsedCredits  sql.NullString `json:"used_credits"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
