// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_credits

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCreditEntry(ctx context.Context, arg AddCreditEntryParams) (CreditsLedger, error)
	GetOrgCredits(ctx context.Context, orgID uuid.NullUUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
