// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_requests.sql

package db_ai_requests

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAiRequest = `-- name: CreateAiRequest :one
INSERT INTO ai_requests (execution_id, node_id, provider, model, input, output, cost)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, execution_id, node_id, provider, model, input, output, cost, created_at
`

type CreateAiRequestParams struct {
	ExecutionID uuid.NullUUID         `json:"execution_id"`
	NodeID      sql.NullString        `json:"node_id"`
	Provider    string                `json:"provider"`
	Model       string                `json:"model"`
	Input       pqtype.NullRawMessage `json:"input"`
	Output      pqtype.NullRawMessage `json:"output"`
	Cost        sql.NullString        `json:"cost"`
}

func (q *Queries) CreateAiRequest(ctx context.Context, arg CreateAiRequestParams) (AiRequest, error) {
	row := q.queryRow(ctx, q.createAiRequestStmt, createAiRequest,
		arg.ExecutionID,
		arg.NodeID,
		arg.Provider,
		arg.Model,
		arg.Input,
		arg.Output,
		arg.Cost,
	)
	var i AiRequest
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.NodeID,
		&i.Provider,
		&i.Model,
		&i.Input,
		&i.Output,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}

const getAiRequest = `-- name: GetAiRequest :one
SELECT id, execution_id, node_id, provider, model, input, output, cost, created_at FROM ai_requests WHERE id = $1
`

func (q *Queries) GetAiRequest(ctx context.Context, id uuid.UUID) (AiRequest, error) {
	row := q.queryRow(ctx, q.getAiRequestStmt, getAiRequest, id)
	var i AiRequest
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.NodeID,
		&i.Provider,
		&i.Model,
		&i.Input,
		&i.Output,
		&i.Cost,
		&i.CreatedAt,
	)
	return i, err
}
