// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_ai_requests

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AiRequest struct {
	ID          uuid.UUID             `json:"id"`
	ExecutionID uuid.NullUUID         `json:"execution_id"`
	NodeID      sql.NullString        `json:"node_id"`
	Provider    string                `json:"provider"`
	Model       string                `json:"model"`
	Input       pqtype.NullRawMessage `json:"input"`
	Output      pqtype.NullRawMessage `json:"output"`
	Cost        sql.NullString        `json:"cost"`
	CreatedAt   sql.NullTime          `json:"created_at"`
}
