// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_ai_requests

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAiRequest(ctx context.Context, arg CreateAiRequestParams) (AiRequest, error)
	GetAiRequest(ctx context.Context, id uuid.UUID) (AiRequest, error)
}

var _ Querier = (*Queries)(nil)
