// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_workflows

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createWorkflowStmt, err = db.PrepareContext(ctx, createWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWorkflow: %w", err)
	}
	if q.deleteWorkflowStmt, err = db.PrepareContext(ctx, deleteWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteWorkflow: %w", err)
	}
	if q.getWorkflowStmt, err = db.PrepareContext(ctx, getWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query GetWorkflow: %w", err)
	}
	if q.listWorkflowsByOrgStmt, err = db.PrepareContext(ctx, listWorkflowsByOrg); err != nil {
		return nil, fmt.Errorf("error preparing query ListWorkflowsByOrg: %w", err)
	}
	if q.updateWorkflowStmt, err = db.PrepareContext(ctx, updateWorkflow); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateWorkflow: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createWorkflowStmt != nil {
		if cerr := q.createWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWorkflowStmt: %w", cerr)
		}
	}
	if q.deleteWorkflowStmt != nil {
		if cerr := q.deleteWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteWorkflowStmt: %w", cerr)
		}
	}
	if q.getWorkflowStmt != nil {
		if cerr := q.getWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getWorkflowStmt: %w", cerr)
		}
	}
	if q.listWorkflowsByOrgStmt != nil {
		if cerr := q.listWorkflowsByOrgStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listWorkflowsByOrgStmt: %w", cerr)
		}
	}
	if q.updateWorkflowStmt != nil {
		if cerr := q.updateWorkflowStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateWorkflowStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                     DBTX
	tx                     *sql.Tx
	createWorkflowStmt     *sql.Stmt
	deleteWorkflowStmt     *sql.Stmt
	getWorkflowStmt        *sql.Stmt
	listWorkflowsByOrgStmt *sql.Stmt
	updateWorkflowStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                     tx,
		tx:                     tx,
		createWorkflowStmt:     q.createWorkflowStmt,
		deleteWorkflowStmt:     q.deleteWorkflowStmt,
		getWorkflowStmt:        q.getWorkflowStmt,
		listWorkflowsByOrgStmt: q.listWorkflowsByOrgStmt,
		updateWorkflowStmt:     q.updateWorkflowStmt,
	}
}
