// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_workflows

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Workflow struct {
	ID          uuid.UUID       `json:"id"`
	OrgID       uuid.NullUUID   `json:"org_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Definition  json.RawMessage `json:"definition"`
	Version     sql.NullInt32   `json:"version"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

type WorkflowVersion struct {
	ID         uuid.UUID       `json:"id"`
	WorkflowID uuid.NullUUID   `json:"workflow_id"`
	Definition json.RawMessage `json:"definition"`
	Version    int32           `json:"version"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}
