// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_workflows

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteWorkflow(ctx context.Context, id uuid.UUID) error
	GetWorkflow(ctx context.Context, id uuid.UUID) (Workflow, error)
	ListWorkflowsByOrg(ctx context.Context, orgID uuid.NullUUID) ([]Workflow, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
