// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db_workflows

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (org_id, name, description, definition, version)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, description, definition, version, created_at, updated_at
`

type CreateWorkflowParams struct {
	OrgID       uuid.NullUUID   `json:"org_id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Definition  json.RawMessage `json:"definition"`
	Version     sql.NullInt32   `json:"version"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.queryRow(ctx, q.createWorkflowStmt, createWorkflow,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.Version,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows WHERE id=$1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteWorkflowStmt, deleteWorkflow, id)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, org_id, name, description, definition, version, created_at, updated_at FROM workflows WHERE id = $1
`

func (q *Queries) GetWorkflow(ctx context.Context, id uuid.UUID) (Workflow, error) {
	row := q.queryRow(ctx, q.getWorkflowStmt, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowsByOrg = `-- name: ListWorkflowsByOrg :many
SELECT id, org_id, name, description, definition, version, created_at, updated_at FROM workflows WHERE org_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListWorkflowsByOrg(ctx context.Context, orgID uuid.NullUUID) ([]Workflow, error) {
	rows, err := q.query(ctx, q.listWorkflowsByOrgStmt, listWorkflowsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name=$2, description=$3, definition=$4, version=$5, updated_at=now()
WHERE id=$1
RETURNING id, org_id, name, description, definition, version, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description sql.NullString  `json:"description"`
	Definition  json.RawMessage `json:"definition"`
	Version     sql.NullInt32   `json:"version"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.queryRow(ctx, q.updateWorkflowStmt, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.Version,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
